version: "3.9"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    environment:
      - TZ
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_WATCH_FIRSTCHECKNOTIF=true
      - DIUN_NOTIF_TELEGRAM_TOKEN
      - DIUN_NOTIF_TELEGRAM_CHATIDS
      - DIUN_NOTIF_TELEGRAM_TEMPLATEBODY
    volumes:
      - "diun-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

volumes:
  diun-data:
