---
- name: infra
  hosts: raspi
  become: true
  become_user: root

  tasks:
    - name: Upgrade Kernel and Setup Unattended upgrades
      include_role:
        name: apt-upgrade
    - name: Install/Remove basic packages and configure Git
      include_role:
        name: apt-manage-packages
    # - name: Increase SWAP Size
    #   include_role:
    #     name: set-swap-size
    #   vars:
    #     swap_size: 2048
    - name: Disable SWAP and move all logs to tmpfs to reduce SD Card writes
      include_role:
        name: set-min-sdcard-write
    - name: Reset SSH Login Message Of The Day
      include_role:
        name: reset-motd
    - name: Configure NTP Fallback URLs to reduce time drift
      include_role:
        name: set-ntp
    - name: Configure any additional WiFi passwords if needed
      include_role:
        name: configure-wifi-passwords
      vars:
        wifis:
        - ssid: "PaiSpot"
          password: "Pai@Almere"
    - name: Opinionated Configuration of ZSH with Starship and OhMyZSH
      include_role:
        name: set-zshrc
      vars:
        zsh_user: pi
    # - name: Install BrosTred Wifi Adaptor Drivers
    #   include_role:
    #     name: install-brostrend
    # - name: Add a Static IP DHCP Configuration for RASPI (Use Raspi as a client)
    #   include_role:
    #     name: set-static-ip
    #   vars:
    #     interface: eth0
    #     static_ip: 192.168.2.222
    #     router_ip: 192.168.2.254
    #     domain_name_servers: 1.1.1.1,8.8.8.8
    # - name: Install Easytether to tunnel data through Mobile if Tethering is not allowed
    #   include_role:
    #     name: install-easytether
    # - name: Install RaspAP and Configure Raspi as a Hotspot Router
    #   include_role:
    #     name: setup-hostapd
    #   vars:
    #     interface: "wlan1"
    #     wlan_device: "brostrend"
    #     wifi_mode: "5GHz"
    #     ap_subnet: "192.168.0.0/24"
    #     ap_router_ip: "192.168.0.1"
    #     dhcp_start_ip: "192.168.0.10"
    #     dhcp_end_ip: "192.168.0.200"
    #     country_code: "NL"
    #     SSID: "PaiFi"
    #     password: "Pai@Almere"
    #     web_dir: /var/www/html
    - name: Mount Attached Disks
      include_role:
        name: mount-disks
      vars:
        mounts:
        - name: Seagate
          uuid: 9C4AD6B64AD68C80
          fstype: ntfs
    - name: Pip Install dependencies for docker
      include_role:
        name: pip-install-docker-deps
    - name: Install docker
      include_role:
        name: docker
      vars:
        docker_user: pi
    # - name: Install docker-compose
    #   include_role:
    #     name: docker-compose
    #   vars:
    #     # https://github.com/docker/compose/releases
    #     docker_compose_version: v2.18.1
  
  post_tasks:
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      reboot:
        msg: Rebooting due to a kernel update
      when: reboot_required_file.stat.exists
