---
- name: infra
  hosts: raspi
  become: true
  become_user: root

  vars:
    pip_executable: /usr/bin/pip3
    docker_user: pi
    docker_compose_version: v2.14.2
    mounts:
    - name: Seagate
      uuid: 9C4AD6B64AD68C80
      fstype: ntfs

  roles:
    - aptupgrade
    - dependencies
    - mount-disks
    - pipinstall
    - docker
    - docker-compose

  post_tasks:
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      reboot:
        msg: Rebooting due to a kernel update
      when: reboot_required_file.stat.exists
