---
- name: infra
  hosts: raspi
  become: true
  become_user: root

  vars:
    zsh_user: pi
    docker_user: pi
    docker_compose_version: v2.14.2
    static_ip: "192.168.2.222"
    router_ip: "192.168.2.254"
    mounts:
    - name: Seagate
      uuid: 9C4AD6B64AD68C80
      fstype: ntfs

  roles:
    - apt-upgrade
    - apt-manage-packages
    - set-zshrc
    - set-motd
    - set-static-ip
    - set-ntp
    - set-swap-size
    - mount-disks
    - pip-install
    - docker
    - docker-compose

  post_tasks:
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      reboot:
        msg: Rebooting due to a kernel update
      when: reboot_required_file.stat.exists
