---
- name: infra
  hosts: raspi
  become: true
  become_user: root

  vars:
    pip_executable: /usr/bin/pip3
    docker_user: pi
    docker_compose_version: "v2.14.2"

  roles:
    - aptupgrade
    - pipinstall
    - docker
    - docker-compose
