version: "3.6"
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx128m -Xms128m"
      discovery.type: single-node
    volumes:
      - elastic-data:/usr/share/elasticsearch/data/
    networks:
      - elk
    ports:
      - 9200:9200
    restart: unless-stopped

  kibana:
    depends_on: [elasticsearch]
    image: kibana:7.16.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk
    ports:
      - 5601:5601
    restart: unless-stopped

  filebeats:
    depends_on: [elasticsearch, kibana]
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeats
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk
    ports:
      - 9600:9600
    user: root
    restart: unless-stopped

volumes:
  elastic-data:

networks:
  elk:
