filebeat.modules:
  - module: elasticsearch

filebeat.autodiscover.providers:
  - type: docker
    hints.enabled: true

filebeat.inputs:
  - type: log
    enabled: false
    paths:
      - /var/log/*.log

output.elasticsearch:
  hosts: ["http://localhost:9200"]

setup.kibana:
  host: "http://localhost:5601"
  
