# sudo nmcli c mod "{{ ssid }}" ipv4.addresses {{ static_ip }}/24 ipv4.method manual
# sudo nmcli con mod "{{ ssid }}" ipv4.gateway {{ router_ip }}
# sudo nmcli con mod "{{ ssid }}" ipv4.dns "{{ domain_name_servers }}"
