---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: true
    cache_valid_time: 86400 # One day
    autoremove: yes
    force_apt_get: true
  register: apt_stream
  async: 1000
  poll: 0

- name: 'apt stream async output'
  async_status:
    jid: "{{ apt_stream.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30

- name: Install unattended upgrades package.
  apt:
    name: unattended-upgrades
    state: present
    force_apt_get: true

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
