version: "3.9"
services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    volumes:
      - alist-data:/opt/alist/data
      - ${MOUNT_PATH}:/hdd
    ports:
      - 5244:5244
    restart: unless-stopped
volumes:
  alist-data: