version: "3.9"

networks:
  dns-net:
    ipam:
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    hostname: "unbound"
    networks:
      dns-net:
        ipv4_address: 10.2.0.200
    restart: unless-stopped

  pihole:
    depends_on: [unbound]
    image: pihole/pihole:2022.12
    container_name: pihole
    environment:
      - TZ
      - WEBPASSWORD=admin
      - PIHOLE_DNS_=10.2.0.200;10.2.0.200 # Unbound IPs
      - DNSMASQ_LISTENING=all
    volumes:
      - "pihole-config:/etc/pihole/"
      - "pihole-dnsmasq:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
    hostname: pihole
    dns:
      - 10.2.0.200 # Points to unbound
    networks:
      dns-net:
        ipv4_address: 10.2.0.100
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    restart: unless-stopped

  # wireguard:
  #   depends_on: [unbound, pihole]
  #   image: linuxserver/wireguard
  #   container_name: wireguard
  #   environment:
  #     - PUID
  #     - PGID
  #     - TZ
  #     - SERVERURL=auto
  #     - SERVERPORT=51820
  #     - PEERS=redmi8,redmi10,guest # How many peers to generate for you (clients)
  #     - ALLOWEDIPS=0.0.0.0/0
  #     - PEERDNS=10.2.0.100
  #     - INTERNAL_SUBNET=10.6.0.0
  #   volumes:
  #     - /lib/modules:/lib/modules
  #     - wireguard-config:/config
  #   networks:
  #     dns-net:
  #       ipv4_address: 10.2.0.50
  #   ports:
  #     - "51820:51820/udp"
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   dns:
  #     - 10.2.0.100 # Points to pihole
  #     - 10.2.0.200 # Points to pihole
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   restart: unless-stopped

  wg-easy:
    depends_on: [unbound, pihole]
    image: weejewel/wg-easy
    container_name: wireguard
    environment:
      - WG_HOST=77.163.167.54
      - PASSWORD=${WG_PASSWORD}
      - WG_DEFAULT_DNS=10.2.0.100
      - WG_MTU=1420
      - WG_ALLOWED_IPS=0.0.0.0/0,::/0
    volumes:
      - wireguard-config:/etc/wireguard
    networks:
      dns-net:
        ipv4_address: 10.2.0.50
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    dns:
      - 10.2.0.100 # Points to pihole
      - 10.2.0.200 # Points to pihole
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

volumes:
  wireguard-config:
  pihole-config:
  pihole-dnsmasq: