---
- name: portainer
  hosts: raspi
  gather_facts: false

  vars:
    services_local_path: ../../services
    services_remote_path: /home/dhananjaipai
    service: portainer
    repo: https://github.com/arpoojaprasannan/raspi-homeserver
    branch: release
    services_absolute_path: services # Path relative to root of the repo above

  roles:
    - docker-compose-up # Installs service portainer from ../../services/portainer path
    - gather-stacks # Finds all services under ../../services path and populates the stacks array
    - configure-portainer # Sets variables portainer_token and endpoint_id
    - install-stacks # Uses portainer_token and endpoint_id to create new stacks based on services variables defined above
