---
- name: Ensure pip packages are installed.
  pip:
    name:
      - docker
      - PyYAML
    state: latest
    executable: "{{ pip_executable }}"
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1 
