version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - portainer-data:/data
    ports:
      - 9443:9443
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

volumes:
  portainer-data:
