---
- name: Ensure old versions of Docker are not installed.
  apt:
    name:
      - docker
      - docker-engine
    force_apt_get: true
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
    state: present
    force_apt_get: true

- name: Add Docker apt key.
  ansible.builtin.get_url:
    url: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
    force: true
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install Docker packages.
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    force_apt_get: true
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started

- name: Add {{ docker_user }} user to "docker" group
  user:
    name: "{{ docker_user }}"
    group: "docker"
    append: yes
