version: "3.9"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - ./assets:/www/assets
    ports:
      - 80:8080
    user: 1000:1000 # default
    restart: unless-stopped
